"id","artist","year-made","painting-name","image-link"
1,"Osaias Beer the Elder",1615,"Flowers in a porcelain Wan-Li Vase","flowers.jpeg"
2,"Canaletto",1740,"Venice: The Grand Canal","canal.jpeg"
3,"Alexandre-Hyacinthe Dunouy",1800,"Panoramic View of the Bay of Naples","naples.jpeg"
4,"John Constable",1821,"The Hay Wain","haywain.jpeg"
5,"Jackson Pollock",1935,"Going West","goingwest.jpeg"
6,"James Thornhill",1726,"Painted Hall","paintedhall.jpeg"
